name: Har Pito
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download Trailscale.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/tailscale-v3-stable-windows-amd64.zip -OutFile tailscale.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/start.bat -OutFile push.bat
    - name: Extract Tailscale File.
      run: Expand-Archive tailscale.zip
    - name: Connect Tailscale.
      run: .\tailscale\tailscale.exe authtoken $Env:TAILSCALE_AUTH_KEY
      env:
        TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
    - name: Windows10 RDP.
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\tailscale\tailscale.exe tcp --region ap 3389"'
    - name: Connect RDP.
      run: cmd /c start.bat
    - name: win10 RDP.
      run: cmd /c loop.bat
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: Yanzz"
          Write-Host "Password: $(echo $env:RDP_CREDS)"
          Write-Host "==================`n"
          
          # Keep runner active indefinitely (or until manually cancelled)
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
